# Generated by Django 5.0 on 2024-02-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_messages', '0003_alter_contact_email_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='message_text',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sent',
            new_name='sent_time',
        ),
    ]
