# Generated by Django 5.0.2 on 2024-02-23 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_messages', '0004_rename_message_contact_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
